theme: jekyll-theme-cayman
title: Git Adventure
description: Uma jornada interativa para aprender Git através de desafios práticos e missões envolventes
show_downloads: true
github:
  repository_url: https://github.com/tatyquebralayout/GitAdventure
  is_project_page: true
  source:
    branch: "master"
    path: "docs"
baseurl: "/GitAdventure"
url: "https://tatyquebralayout.github.io"
google_analytics: 